nobel/nobel/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('nobel.winners.urls')),
    path('admin/', admin.site.urls),
]

nobel/nobel/winners/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'winners'
urlpatterns = [
    path('', views.home, name='home'),
    path('winners/', views.list_winners, name='winners-list'),
    path('countries/', views.list_countries, name='countries-list'),
    path('categories/', views.list_categories, name='categories-list'),
    path('categories/<slug:category>/', views.category_winners, name='category-winner-list'),
    path('api/', views.api, name='api'),
    path('windapi/', views.windapi, name='windapi'),
]

nobel/nobel/winners/models.py
from django.db import models


GENDER_CHOICES=(
    ('male', 'Male'),
    ('female', 'Female'),
)


class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class WindAverage(models.Model):

    time = models.DateTimeField()
    speed = models.IntegerField()

    class Meta:
        ordering = ('time',)

   

    def to_json(self):
        return {
            "time": self.time,
            "speed": self.speed,
        }


class Country(models.Model):
    name = models.CharField(max_length=100)
    alpha_code = models.CharField(max_length=3, blank=True, null=True)
    numeric_code = models.CharField(max_length=3, blank=True, null=True)
    lat = models.CharField(max_length=10, blank=True, null=True)
    lng = models.CharField(max_length=10, blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

    def to_json(self):
        return {
            "name": self.name,
            "alpha_code": self.alpha_code,
            "numeric_code": self.numeric_code,
            "lat": self.lat,
            "lng": self.lng,
        }
    



class Person(models.Model):
    name = models.CharField(max_length=100)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    dob = models.DateField()

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Winner(models.Model):
    person = models.ForeignKey(Person, "CASCADE")
    category = models.ForeignKey(Category, "CASCADE")
    country = models.ForeignKey(Country, "CASCADE")
    year = models.PositiveIntegerField()

    def __str__(self):
        return "{} {} - {} ({})".format(self.person.name, self.category, self.country, self.year)
    
    def to_json(self):
        return {
            "name": self.person.name,
            "gender": self.person.gender,
            "category": self.category.name,
            "country": self.country.to_json(),
            "year": self.year,
        }

nobel/nobel/winners/views.py
from django.core import serializers
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.http import JsonResponse

from . import models


def home(request):
    return render(request, "winners/homecopy.html", {
        'windaverages': models.WindAverage.objects.all(),
      
    })


def list_winners(request):
    filter_by = request.GET.get('filter')
    filter_val = request.GET.get('val')
    filter_breadcrumb_name = None
    filter_breadcrumb_url = None
    
    objects = models.Winner.objects.all()

    if filter_by and filter_val:
        if filter_by == 'country':
            objects = objects.filter(country__name__iexact=filter_val)
            filter_breadcrumb_name = "Countries"
            filter_breadcrumb_url = reverse("winners:countries-list")
        if filter_by == 'category':
            objects = objects.filter(category__name__iexact=filter_val)
            filter_breadcrumb_name = "Categories"
            filter_breadcrumb_url = reverse("winners:categories-list")

    return render(request, "winners/list.html", {
        "list_type": "Winners",
        "objects": objects,
        "filter_by": filter_by,
        "filter_val": filter_val,
        "filter_breadcrumb_name": filter_breadcrumb_name,
        "filter_breadcrumb_url": filter_breadcrumb_url,
    })


def list_countries(request):
    return render(request, "winners/list.html", {
        "list_type": "Countries",
        "filter_by": "country",
        "objects": models.Country.objects.all()
    })


def list_categories(request, name=None):
    objects = models.Category.objects.all()
    if name:
        objects = objects.filter(name=name)
    return render(request, "winners/list.html", {
        "list_type": "Categories",
        "filter_by": "category",
        "objects": objects,
    })


def category_winners(request, category):
    category = get_object_or_404(models.Category, name=category)
    return render(request, "winners/category_winners.html", {
        "category": category,
        "objects": category.winner_set.all(),
    })

def windapi(request):
    
    windaverages = models.WindAverage.objects.all()

   
    data = {
        "windaverages": [w.to_json() for w in windaverages],
    }

    return JsonResponse(data)




def api(request):
    category = request.GET.get('category')
    country = request.GET.get('country')
    gender = request.GET.get('gender')
    
    winners = models.Winner.objects.select_related('category', 'country', 'person')

    if category:
        winners = winners.filter(category__name=category)
    
    if country:
        winners = winners.filter(country__name=country)
    
    if gender:
        winners = winners.filter(person__gender=gender)
    
    # Now that we have filtered the winners down get only the countries that
    # are relevant to our winners
    country_ids = winners.values_list('country_id', flat=True)

    # Use that list of ids to filter down a country queryset
    countries = models.Country.objects.filter(id__in=country_ids)

    # Get json compatible representation of our countries in a list
    country_data = [c.to_json() for c in countries]

    # Count the number of winners using an annotation...
    # Group our winners by country by selecting the country name field
    winning_counts = winners.values('country__name').annotate(winner_count=Count('country__name'))

    # Convert winning counts from a list to a dictionary for lookup
    winners_by_country = {x["country__name"]: x["winner_count"] for x in winning_counts}
    
    # Add out winner count to our country data
    for c in country_data:
        c["winners"] = winners_by_country.get(c["name"], 0)

    data = {
        "winners": [w.to_json() for w in winners],
        "countries": country_data,
    }

    return JsonResponse(data)

nobel/nobel/winners/templates/winners/base.html
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    

    

   <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootswatch/4.0.0/superhero/bootstrap.min.css">


  </head>
  <body>
    {% block body %}
     <title>Wind Data</title>
     <h1>Sullivan's Island, SC Wind</h1>
     <h4>Hourly wind data, so you know which kite to use at what time</h4>


    
    <div id="chart"></div>
    <br>
    <center>Before you can kite, you should guage the wind below and use the right kite for the precise wind range</center>
    <div id="chart2"></div>
    <div class="image"></div>​
   




      
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="https://unpkg.com/topojson@3"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/c3/0.5.4/c3.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.min.css" rel="stylesheet" />
    {% block script %}{% endblock %}
  </body>
</html>

nobel/nobel/winners/templates/winners/category_winners.html
{% extends "winners/base.html" %}

{% block content %}
    
{% endblock %}

nobel/nobel/winners/templates/winners/home.html
{% extends "winners/base.html" %}
{% load static %}

<style>
#chart, chart2{
    min-height:500px;
    width:100%;
}
div.image {
   content:url(http://placehold.it/350x150);
}​
body {
	background-color: lightblue;	

}
img.resize {
  max-width:20%;
  max-height:20%;
}
.c3-legend-item {
 fill: #a8a8a8;
}
</style>
{% block breadcrumbs %}
    <li class="breadcrumb-item active">Home</li>
{% endblock %}

{% block content %}  


   
   
{% endblock %}

{% block script %}
    <script src="{% static "winners/js/bar.js" %}"></script>
    <script src="{% static "winners/js/home.js" %}"></script>
{% endblock %}

nobel/nobel/winners/templates/winners/homecopy.html
{% extends "winners/base.html" %}
{% load static %}

{% block breadcrumbs %}
    <li class="breadcrumb-item active">Home</li>
{% endblock %}

{% block content %}  
    <div class="row">
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        WindyData
                    </h5>
                    <p class="card-text">
                        <a href="{% url "winners:winners-list" %}">{{ winners.count }} Winners</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        Countries
                    </h5>
                    <p class="card-text">
                        <a href="{% url "winners:countries-list" %}">{{ countries.count }} Countries</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">
                        Categories
                    </h5>
                    <p class="card-text">
                        <a href="{% url "winners:categories-list" %}">{{ categories.count }} Categories</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-4">
            <h4>Category</h4>
            <select name="category" id="sel-category">
                    <option value="">All</option>
                {% for category in categories %}
                    <option value="{{ category.name }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-4">
            <h4>Country</h4>
            <select name="country" id="sel-country">
                <option value="">All</option>
                {% for country in countries %}
                    <option value="{{ country.name }}">{{ country.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="col-4">
            <h4>Gender</h4>
            <select name="gender" id="sel-gender">
                <option value="">All</option>
                {% for gender in genders %}
                    <option value="{{ gender.0 }}">{{ gender.1 }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            <div id="nobel-bar"></div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-12">
            <pre id="raw-json"></pre>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static "winners/js/bar.js" %}"></script>
    <script src="{% static "winners/js/home.js" %}"></script>
{% endblock %}

nobel/nobel/winners/templates/winners/list.html
{% extends "winners/base.html" %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url "winners:home" %}">Home</a></li>
    <li class="breadcrumb-item active">List</li>
{% endblock %}

{% block content %}
    
   
{% endblock %}